#!/bin/bash

source "$CONFIG_DIR/colors.sh"
source "$CONFIG_DIR/var.sh"

AEROSPACE="$(which aerospace)"
FOCUSED=$("$AEROSPACE" list-workspaces --focused 2>/dev/null || echo "1")

sketchybar --bar height=30 \
                 blur_radius=0 \
                 position=top \
                 y_offset=5 \
                 sticky=off \
                 padding_left=10 \
                 padding_right=10 \
                 color=$BAR_COLOR

sketchybar --add event aerospace_workspace_change

sketchybar --default icon.font="3270 Nerd Font:Regular:13" \
                     icon.color=$WHITE \
                     background.color=$ITEM_BG_COLOR \
                     label.font="3270 Nerd Font:Regular:13" \
                     label.color=$WHITE \
                     padding_left=5 \
                     padding_right=5 \
                     label.padding_left=5 \
                     label.padding_right=5 \
                     icon.padding_left=5 \
                     icon.padding_right=5

sketchybar --hotload true

# Left
source $ITEM_DIR/update.sh
source $ITEM_DIR/aerospace.sh
sketchybar --add item separator left \
           --set separator label="|"

source $ITEM_DIR/front_app.sh

# Right
source $ITEM_DIR/clock.sh
source $ITEM_DIR/battery.sh
source $ITEM_DIR/input_source.sh

sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE="$FOCUSED"

sketchybar --update
